export default {
  products: [
    {
      _id: '1',
      name: 'Crop Top',
      category: 'Shirts',
      image: '/images/product-1.jpg',
      price: 59,
      brand: 'FENA',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '2',
      name: 'Gown',
      category: 'Dresses',
      image: '/images/product-2.jpg',
      price: 70,
      brand: 'Silica',
      rating: 5,
      numReviews: 51,
    },
    {
      _id: '3',
      name: 'Jeans Trouser',
      category: 'Denim',
      image: '/images/product-3.jpg',
      price: 59,
      brand: 'Adidos',
      rating: 4,
      numReviews: 45,
    },
    {
      _id: '4',
      name: 'Puffer Jackets',
      category: 'Jackets',
      image: '/images/product-4.jpg',
      price: 90,
      brand: 'Under Armour',
      rating: 2.5,
      numReviews: 198,
      countInStock: 6,
    },
    {
      _id: '5',
      name: 'Coats',
      category: 'Jackets',
      image: '/images/product-5.jpg',
      price: 119,
      brand: 'Champion',
      rating: 3.5,
      numReviews: 89,
      countInStock: 6,
    },
    {
      _id: '6',
      name: 'Skirts',
      category: "Minis",
      image: '/images/product-6.jpg',
      price: 85,
      brand: 'Minis',
      rating: 4.5,
      numReviews: 45,
      countInStock: 6,
    },
  ],
};
